### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by alexusgracia** [alexusgracia/hackernews-asw#16]
Registre / Login d'usuaris. Una diferència respecte al HN original: per fer el registre i el login heu d'utilitzar el "Sign In" extern de Google, Twitter, GitHub o similar (només un d'aquests). Mireu d'utilitzar gems que proporcionin aquesta funcionalitat. De fet, no cal que hi hagi diferència entre login i registre: quan l'usuari es loguegi per primera vegada es dóna d'alta com a usuari del sistema.

**Comment by alexcatmu** [comment]
#b45bea833f9eddfc8d6236552343cadcd0060cd5
